#pragma once

#include <string>

namespace db {

class Slice;

// FilterPolicy builds compact filters from a sorted set of keys.
// The database consults these filters before reading data blocks so it can
// skip disk reads when a key is definitely absent.
class FilterPolicy {
public:
  virtual ~FilterPolicy();

  // Returns the policy name. If the filter encoding changes incompatibly,
  // this name must change as well so old filters are not misinterpreted.
  virtual const char* Name() const = 0;

  // Appends a filter summarizing keys[0, n) to *dst.
  // keys may contain duplicates and are ordered by the user comparator.
  // Implementations must append to *dst instead of replacing its contents.
  virtual void CreateFilter(const Slice* keys, int n, std::string* dst) const = 0;

  // Returns true if key may be present in the filter generated by
  // CreateFilter(). False means the key is definitely absent.
  virtual bool KeyMayMatch(const Slice& key, const Slice& filter) const = 0;
};

// Returns a bloom filter policy using approximately bits_per_key bits per key.
// A value of 10 is a reasonable default and yields about a 1% false positive
// rate.
//
// Callers own the returned object and must delete it after any database using
// it has been closed.
//
// If you use a comparator that ignores part of the user key, you must provide
// a matching custom FilterPolicy instead of using this helper.
const FilterPolicy* NewBloomFilterPolicy(int bits_per_key);

}  // namespace db
