#pragma once

#include <cstddef>

#include "comparator.h"

namespace db {

class Cache;
class Env;
class FilterPolicy;
class Logger;
class Snapshot;

// DB contents are stored in a set of blocks, each of which holds a
// sequence of key/value pairs. Each block may be compressed before
// being stored in a file. The following enum describes which
// compression method (if any) is used to compress a block.
enum CompressionType {
  // NOTE: do not change the values of existing entries, as these are
  // part of the persistent format on disk.
  kNoCompression = 0x0,
  kSnappyCompression = 0x1,
  kZstdCompression = 0x2,
};

// Options to control the behavior of a database.
struct Options {
  Options() = default;

  // Comparator used to define the order of keys in the table.
  // Default: a comparator that uses lexicographic byte-wise ordering.
  //
  // REQUIRES: The client must ensure that the comparator supplied
  // here has the same name and orders keys exactly the same as the
  // comparator provided to previous open calls on the same DB.
  const Comparator* comparator = BytewiseComparator();

  // If true, the database will be created if it is missing.
  bool create_if_missing = false;

  // If true, an error is raised if the database already exists.
  bool error_if_exists = false;

  // If true, the implementation will do aggressive checking of the
  // data it is processing and will stop early if it detects any
  // errors. This may have unforeseen ramifications: for example, a
  // corruption of one DB entry may cause a large number of entries to
  // become unreadable or for the entire DB to become unopenable.
  bool paranoid_checks = false;

  // Use the specified object to interact with the environment,
  // e.g. to read/write files, schedule background work, etc.
  Env* env = nullptr;

  // Any internal progress/error information generated by the db will
  // be written to info_log if it is non-null.
  Logger* info_log = nullptr;

  // Amount of data to build up in memory (backed by an unsorted log
  // on disk) before converting to a sorted on-disk file.
  //
  // Larger values increase performance, especially during bulk loads.
  // Up to two write buffers may be held in memory at the same time,
  // so you may wish to adjust this parameter to control memory usage.
  // Also, a larger write buffer will result in a longer recovery time
  // the next time the database is opened.
  size_t write_buffer_size = 4 * 1024 * 1024;

  // Number of open files that can be used by the DB. You may need to
  // increase this if your database has a large working set.
  int max_open_files = 1000;

  // If non-null, use the specified cache for blocks.
  Cache* block_cache = nullptr;

  // Approximate size of user data packed per block. Note that the
  // block size specified here corresponds to uncompressed data.
  size_t block_size = 4 * 1024;

  // Number of keys between restart points for delta encoding of keys.
  int block_restart_interval = 16;

  // The target file size before switching to a new one.
  size_t max_file_size = 2 * 1024 * 1024;

  // Compress blocks using the specified compression algorithm.
  CompressionType compression = kSnappyCompression;

  // Compression level for zstd.
  // Currently only the range [-5, 22] is supported. Default is 1.
  int zstd_compression_level = 1;

  // EXPERIMENTAL: If true, append to existing MANIFEST and log files
  // when a database is opened. This can significantly speed up open.
  bool reuse_logs = false;

  // If non-null, use the specified filter policy to reduce disk reads.
  const FilterPolicy* filter_policy = nullptr;
};

// Options that control read operations.
struct ReadOptions {
  // If true, all data read from underlying storage will be
  // verified against corresponding checksums.
  bool verify_checksums = false;

  // Should the data read for this iteration be cached in memory?
  // Callers may wish to set this field to false for bulk scans.
  bool fill_cache = true;

  // If "snapshot" is non-null, read as of the supplied snapshot.
  // If "snapshot" is null, use an implicit snapshot of the state at
  // the beginning of this read operation.
  const Snapshot* snapshot = nullptr;
};

// Options that control write operations.
struct WriteOptions {
  WriteOptions() = default;

  // If true, the write will be flushed from the operating system
  // buffer cache before the write is considered complete.
  bool sync = false;
};

}  // namespace db
